msgid ""
msgstr ""
"Project-Id-Version: scikit-learn\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-03-31 11:24-0400\n"
"PO-Revision-Date: 2021-06-06 23:44\n"
"Last-Translator: \n"
"Language-Team: Spanish\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.9.0\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: scikit-learn\n"
"X-Crowdin-Project-ID: 450526\n"
"X-Crowdin-Language: es-ES\n"
"X-Crowdin-File: /main/doc/en/modules/generated/sklearn.exceptions.DataDimensionalityWarning.po\n"
"X-Crowdin-File-ID: 5064\n"
"Language: es_ES\n"

#: ../modules/generated/sklearn.exceptions.DataDimensionalityWarning.rst:2
msgid ":mod:`sklearn.exceptions`.DataDimensionalityWarning"
msgstr ":mod:`sklearn.exceptions`.DataDimensionalityWarning"

#: of sklearn.exceptions.DataDimensionalityWarning:2
msgid "Custom warning to notify potential issues with data dimensionality."
msgstr "Advertencia personalizada para notificar posibles problemas con la dimensionalidad de los datos."

#: of sklearn.exceptions.DataDimensionalityWarning:4
msgid "For example, in random projection, this warning is raised when the number of components, which quantifies the dimensionality of the target projection space, is higher than the number of features, which quantifies the dimensionality of the original source space, to imply that the dimensionality of the problem will not be reduced."
msgstr "Por ejemplo, en la proyección aleatoria, esta advertencia se lanza cuando el número de componentes, que cuantifica la dimensionalidad del espacio de proyección objetivo, es mayor que el número de características, que cuantifica la dimensionalidad del espacio fuente original, lo que implica que la dimensionalidad del problema no se reducirá."

#: of sklearn.exceptions.DataDimensionalityWarning:10
msgid "Moved from sklearn.utils."
msgstr "Se ha movido de sklearn.utils."

#: of sklearn.exceptions.DataDimensionalityWarning
msgid "Attributes"
msgstr "Atributos"

#: of sklearn.exceptions.DataDimensionalityWarning:27
msgid "**args**"
msgstr "**args**"

#: of sklearn.exceptions.DataDimensionalityWarning:30
msgid "Methods"
msgstr "Métodos"

#: of sklearn.exceptions.DataDimensionalityWarning:34:<autosummary>:1
msgid ":obj:`with_traceback <sklearn.exceptions.DataDimensionalityWarning.with_traceback>`\\"
msgstr ":obj:`with_traceback <sklearn.exceptions.DataDimensionalityWarning.with_traceback>`\\"

#: of sklearn.exceptions.DataDimensionalityWarning.with_traceback:2
#: sklearn.exceptions.DataDimensionalityWarning:34:<autosummary>:1
msgid "Exception.with_traceback(tb) -- set self.__traceback__ to tb and return self."
msgstr "Exception.with_traceback(tb) -- establece self.__traceback__ a tb y devuelve self."

